name = "minideck"
main = "src/worker.js"
compatibility_date = "2026-07-29"

[assets]
directory = "public"
binding = "ASSETS"
html_handling = "none"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*", "/img/*", "/p/*"]

[[d1_databases]]
binding = "DB"
database_name = "minideck"
database_id = "c993c83c-b343-48b6-9391-6a3cd99c5a00"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "minideck"

[[rules]]
type = "Text"
globs = ["**/*.md"]
fallthrough = true

[vars]
LIMIT_IP_PROJECTS = "3"
LIMIT_GLOBAL_PROJECTS = "50"
LIMIT_GLOBAL_TEXT = "300"
LIMIT_GLOBAL_IMAGES = "250"
LIMIT_PROJECT_REVISES = "6"
LIMIT_PROJECT_IMAGES = "15"
LIMIT_PROJECT_RETRIES = "2"
